#d2 --watch memory-bank/schema.d2 memory-bank/schema.svg
# Todo:
# Web link
# Storage link (?)
# Legend

grid-rows: 3
grid-columns: 1

vars: {
    colors: {
        1: "#0496FF"
        2: "#006BE6"
        3: "#FFBC42"
        4: "#D81159"
        5: "#8F2D56"
        gray: "#555555"
    }
}

classes: {
    invisible_group{
        style{
            fill: transparent
            opacity: 0
            stroke: transparent
        }
        label: ""
    }
    server_group{
        style{
            # fill: transparent
            opacity: 0.9
            stroke-dash: 1
            stroke: ${colors.3}
        }
    }
    server: {
        grid-columns: 3
        style: {
            border-radius: 3
            fill: ${colors.3}
            stroke: ${colors.5}
            opacity: 0.8
        }
    }
    icon:{
        style: {
            shadow: true
        }
        label: ""
        shape: image
    }
    net_link: {
        style:{
            stroke: ${colors.5}
            stroke-dash: 10
        }
    }
    web_link:{
        style:{
            fill: ${colors.2}
            stroke: ${colors.5}
        }
    }
}
Internet:{
    shape: cloud
}
Infra: {
    style{
        fill: transparent
        stroke-dash: 5
        stroke: ${colors.2}
    }
    grid-columns: 2
    Cloud:{
        grid-rows: 2 
        grid-columns: 2
        Ebenolt-Mail{
            tooltip: OVH VPS\n4vCPU + 8Go RAM + 75GGo NVMe
            poste{
                class: icon
                icon: pics/poste.png
            }
        }
        Ebenolt-VPS{
            tooltip: OVH VPS\n6vCPU + 12Go RAM + 100Go NVMe
            portainer{
                class: icon
                icon: pics/portainer.png
            }
            npm{
                class: icon
                icon: pics/npm.png
            }
            wireguard {
                class: icon
                icon: pics/wireguard.png
            }
            docmost {
                class: icon
                icon: pics/docmost.png
            }
            homepage {
                class: icon
                icon: pics/homepage.png
            }
            infisical {
                class: icon
                icon: pics/infisical.png
            }
            postgresql {
                class: icon
                icon: pics/postgresql.png
            }
            ntfy {
                class: icon
                icon: pics/ntfy.png
            }
            rallly {
                class: icon
                icon: pics/rallly.png
            }
            tandoor {
                class: icon
                icon: pics/tandoor.png
            }
            umami {
                class: icon
                icon: pics/umami.png
            }
            uptime_kuma {
                class: icon
                icon: pics/uptime_kuma.png
            }
            vaultwarden {
                class: icon
                icon: pics/vaultwarden.png
            }      
        }
    }

    OnPrem: {
        grid-columns: 1
        grid-rows: 2
        infra{
            class: invisible_group
            grid-columns: 3
            grid-rows: 1
            empty {
                class: invisible_group
                width: 800
            }
            Unifi Dream Machine Pro{
                class: icon
                icon: pics/udm.png
                width: 400
                height: 150
                tooltip: Unifi Dream Machine Pro
            }
            NAS{
                class: icon
                icon: pics/qnap.png
                width: 400
                height: 150
                tooltip: QNAP TS X435XeU\n4x4To
            }
        }
        servers{
            class: invisible_group
            grid-columns: 3
            grid-rows: 1
            Ebenolt-Gateway{
                tooltip: Celeron N4100 + 8Go DDR4 + 128Go SD
                portainer{
                    class: icon
                    icon: pics/portainer.png
                }
                npm{
                    class: icon
                    icon: pics/npm.png
                }
                grafana{
                    class: icon
                    icon: pics/grafana.png
                }
                loki{
                    class: icon
                    icon: pics/loki.png
                }
                victoriametrics{
                    class: icon
                    icon: pics/victoriametrics.png
                }
                alloy{
                    class: icon
                    icon: pics/alloy.png
                }
                homebridge{
                    class: icon
                    icon: pics/homebridge.png
                }
                firefox{
                    class: icon
                    icon: pics/firefox.png
                }
            }
            proxmox01{
                tooltip: GMKTek M5 Plus\nR7 5825U + 32 Go DDR4 + 1,5 To NVMe
                style{
                    fill: transparent
                    stroke-dash: 8
                    stroke: ${colors.5}
                }
                Ebenolt-HomeAssistant{
                    HA{
                        class: icon
                        icon: pics/homeassistant.png
                    }
                }
                Ebenolt-Infra{
                    gh_runner{
                        class: icon
                        icon: pics/runner.png
                    }
                }
                Ebenolt-WOL{
                    upsnap{
                        class: icon
                        icon: pics/upsnap.png
                    }
                }
                k8s-node-1{
                    k8s_node{
                        class: icon
                        icon: pics/k8s.png
                    }
                }
                k8s-node-2{
                    k8s_node{
                        class: icon
                        icon: pics/k8s.png
                    }
                }
                k8s-node-3{
                    k8s_node{
                        class: icon
                        icon: pics/k8s.png
                    }
                }
                Ebenolt-Gameserver{
                    amp{
                        class: icon
                        icon: pics/amp.png
                    }
                }
            }
            Ebenolt-Plex{
                tooltip: GMKtek G3\nIntel N100 + 8Go DDR4 + 250Go NVMe
                plex{
                    class: icon
                    icon: pics/plex.png
                }
                sonarr{
                    class: icon
                    icon: pics/sonarr.png
                }
                radarr{
                    class: icon
                    icon: pics/radarr.png
                }
                prowlarr{
                    class: icon
                    icon: pics/prowlarr.png
                }
                gluetun{
                    class: icon
                    icon: pics/gluetun.png
                }
                qbittorrent{
                    class: icon
                    icon: pics/qbittorrent.png
                }
                tautulli{
                    class: icon
                    icon: pics/tautulli.png
                }
                overseerr{
                    class: icon
                    icon: pics/overseerr.png
                }
            }
        }
    }
}

# Internal Network
Infra.OnPrem.infra.Unifi Dream Machine Pro <-> Infra.Cloud.Ebenolt-VPS: Wireguard {
                    label: ""
                    shape: image
                    icon: pics/wireguard.png
                    class: net_link
                }
Infra.OnPrem.infra.Unifi Dream Machine Pro -> Infra.OnPrem.servers.Ebenolt-Plex {class: net_link}
Infra.OnPrem.infra.Unifi Dream Machine Pro -> Infra.OnPrem.servers.Ebenolt-Gateway {class: net_link}
Infra.OnPrem.infra.Unifi Dream Machine Pro -> Infra.OnPrem.servers.proxmox01 {class: net_link}
Infra.OnPrem.infra.Unifi Dream Machine Pro -> Infra.OnPrem.infra.NAS {class: net_link}

# Internet Network
Internet -> Infra.OnPrem.infra.Unifi Dream Machine Pro { label: 82.65.131.158\n10Gbps; class: net_link }
Internet -> Infra.Cloud.Ebenolt-Mail { label: 51.75.23.90\n400Mbps; class: net_link }
Internet -> Infra.Cloud.Ebenolt-VPS { label: 51.38.232.207\n1Gbps; class: net_link}

# Styling
Infra.*{ class: server_group }
Infra.Cloud.* { class : server }
Infra.OnPrem.servers.* { class : server }
Infra.OnPrem.servers.proxmox01.* { class : server}
Infra.OnPrem.servers.proxmox01 { grid-rows: 1; grid-columns: 4}
