version: '3'


volumes:
  dubost-wp-data:
  dubost-db:

services:
  dubost-db:
    image: mariadb:latest
    container_name: dubost-db
    restart: always
    env_file:
      stack.env
    volumes:
      - dubost-db:/var/lib/mysql

  dubost-wp:
    depends_on:
      - dubost-db
    image: wordpress:latest
    container_name: dubost-wp
    restart: always
    ports:
      - "8085:80"
    env_file:
      - stack.env
    environment:
      - WORDPRESS_DB_HOST=dubost-db:3306
    volumes:
      - dubost-wp-data:/var/www/html