version: '3.8'


services:
  stirling-pdf:
    image: frooodle/s-pdf:1.3.2
    ports:
      - '8090:8080'
    volumes:
      - trainingData:/usr/share/tessdata
      - extraConfig:/configs
      - customFiles:/customFiles/
      - logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    container_name: pdf-editor
    restart: always
volumes:
  trainingData:
  extraConfig:
  customFiles:
  logs: