services:
  rallly_db:
    image: postgres:14.2
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rallly:
    image: lukevella/rallly:latest
    restart: always
    depends_on:
      - rallly_db
    ports:
      - 3005:3000
    env_file:
      - stack.env

volumes:
  db-data: