version: "3.8"

volumes:
  uptime_kuma-data:
  
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0-beta.4
    container_name: uptime-kuma
    restart: always
    # ports:
    #   - 3001:3001
    volumes:
    - uptime_kuma-data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 900M
        reservations:
          cpus: '0.5'
          memory: 500M