version: "3.8"

volumes:
  nginx-data:
  nginx-certs:
  firefox-data:

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-data:/data
      - nginx-certs:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M


  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    #  - FIREFOX_CLI=https://doc.anthonin.fr #optional
    volumes:
      - firefox-data:/config
    #ports:
    #  - 3000:3000
    #  - 3001:3001
    shm_size: "512mb"
    restart: unless-stopped
