---
---
- name: Check if GPG key is already imported
  shell: "gpg --list-keys | grep '{{ gpg_id }}'"
  register: gpg_key_check
  failed_when: false
  changed_when: false

- name: Copy GPG key
  copy:
    src: "files/GPG/CICD.asc"
    dest: "~/CICD.asc"
    owner: "{{ final_user }}"
    group: "{{ final_user }}"
    mode: 0700
  become: true
  become_user: "{{ final_user }}"
  no_log: true
  when: "{{ gpg_key_check.stdout == '' }}"

- name: Import GPG private key
  command: >
    gpg --batch --yes --pinentry-mode loopback --import ~/CICD.asc
  become: true
  become_user: "{{ final_user }}"
  when: "{{ gpg_key_check.stdout == '' }}"

- name: Delete GPG private key file
  file:
    path: "~/CICD.asc"
    state: absent
  become: true
  become_user: "{{ final_user }}"
  when: "{{ gpg_key_check.stdout == '' }}"
