backups:
  docker_volumes:
    name: "docker_volumes"
    source_folder: "/var/lib/docker/volumes"
    excluded:
      - "/var/lib/docker/volumes/metadata.db"
      - "/var/lib/docker/volumes/backingFsBlockDev"
    retention_days: "10"

monitoring_tag: "VM"

stack:
  - name: docmost
    file: docmost.yml
    env: docmost.env
  - name: wakeonlan
    file: wakeonlan.yml
  - name: vaultwarden
    file: vaultwarden.yml
    env: vaultwarden.env
