backups:
  docker_volumes:
    name: "docker_volumes"
    source_folder: "/var/lib/docker/volumes"
    excluded:
      - "/var/lib/docker/volumes/metadata.db"
      - "/var/lib/docker/volumes/backingFsBlockDev"
      - "/var/lib/docker/volumes/supervision_prometheus-data/*"
    retention_days: "10"
