backups:
  docker_volumes:
    name: "docker_volumes"
    source_folder: "/var/lib/docker/volumes"
    excluded:
      - "/var/lib/docker/volumes/metadata.db"
      - "/var/lib/docker/volumes/backingFsBlockDev"
      - "/var/lib/docker/volumes/supervision_prometheus-data/*"
    retention_days: "10"
stack:
  - name: docmost
    file: docmost.yml
    env: docmost.env
  - name: infisical
    file: infisical.yml
    env: infisical.env
  - name: supervision
    file: supervision-VPS.yml
  - name: tandoor
    file: tandoor.yml
    env: tandoor.env
  - name: vaultwarden
    file: vaultwarden.yml
    env: vaultwarden.env
  - name: web
    file: web-VPS.yml
    env: web-VPS.env
  - name: wireguard
    file: wireguard.yml
  - name: rallly
    file: rallly.yml
    env: rallly.env
  - name: dubost-wp
    file: dubost-wordpress.yml
    env: dubost-wordpress.env
  # - name: minio
  #   file: minio.yml
  #   env: minio.env

firewall_custom_rules:
  - comment: Web HTTP
    protocol: TCP
    d_port: 80
    action: ACCEPT
    in_if: docker0
  - comment: Web HTTPS
    protocol: TCP
    d_port: 443
    action: ACCEPT
  - comment: SSH
    protocol: TCP
    d_port: 22
    action: ACCEPT
  - comment: SSH Share
    protocol: TCP
    d_port: 222
    action: ACCEPT
  - comment: Wireguard
    protocol: UDP
    d_port: 51820
    action: ACCEPT
