backups:
  docker_volumes:
    name: "docker_volumes"
    source_folder: "/var/lib/docker/volumes"
    excluded:
      - "/var/lib/docker/volumes/metadata.db"
      - "/var/lib/docker/volumes/backingFsBlockDev"
      - "/var/lib/docker/volumes/stack_plex-config/_data/Library/Application Support/Plex Media Server/Metadata/"
      - "/var/lib/docker/volumes/stack_plex-config/_data/Library/Application Support/Plex Media Server/Media/"
    retention_days: "5"
