backups:
  docker_volumes:
    name: "docker_volumes"
    source_folder: "/var/lib/docker/volumes"
    excluded:
      - "/var/lib/docker/volumes/metadata.db"
      - "/var/lib/docker/volumes/backingFsBlockDev"
    retention_days: "5"

monitoring_tag: "VM"

stack:
  - name: wakeonlan
    file: wakeonlan.yml
