backups:
  docker_volumes:
    name: "docker_volumes"
    source_folder: "/var/lib/docker/volumes"
    excluded:
      - "/var/lib/docker/volumes/metadata.db"
      - "/var/lib/docker/volumes/backingFsBlockDev"
      - "/var/lib/docker/volumes/supervision_prometheus-data/*"
      - "/var/lib/docker/volumes/plex_plex-config/*"
      - "/var/lib/docker/volumes/plex_radarr-config/*"
    retention_days: "10"
  old:
    name: "old"
    source_folder: "/home/ebenolt/old"
    excluded: ""
    retention_days: "2"

monitoring_tag: "Server"

stack:
  - name: homebridge
    file: homebridge.yml
  - name: supervision
    file: supervision-Home.yml
    env: supervision-Home.env
  - name: web
    file: web-Home.yml
  - name: n8s
    file: n8n.yml
