---
- name: Upgrade all apt packages
  apt:
    force_apt_get: yes
    upgrade: dist

# - name: Preconf iptables
#   ansible.builtin.debconf:
#     name: iptables-persistent
#     question: iptables-persistent/autosave_v4
#     vtype: boolean
#     value: true

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install additional packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

- name: "Install Python packages"
  pip:
    name: "{{ item }}"
    state: present
    break_system_packages: true
  with_items: "{{ pip_packages }}"

- name: "Install additional Python packages"
  pip:
    name: "{{ item }}"
    state: present
    break_system_packages: true
  with_items: "{{ pip_additional_packages }}"
