---
- name: Install packages
  ansible.builtin.include_tasks: install_packages.yml

- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml
  when: ansible_distribution == "Debian"


- name: Set locale and timezone
  ansible.builtin.include_tasks: set_locales.yml

- name: System configuration
  ansible.builtin.include_tasks: sys_config.yml
