- name: Allow OUT
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: "{{ item }}"
    jump: ACCEPT
  with_items:
    - tcp
    - udp

- name: Allow ping
  ansible.builtin.iptables:
    chain: "{{ item }}"
    protocol: icmp
    jump: ACCEPT
    comment: "Allow ping"
  with_items:
    - INPUT
    - OUTPUT

- name: Allow DNS
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item }}"
    jump: ACCEPT
    source_port: 53
    comment: "Allow DNS"
  with_items:
    - tcp
    - udp

- name: Drop invalid connection
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: INVALID
    jump: ACCEPT

- name: Allow all from whitelisted
  ansible.builtin.iptables:
    chain: INPUT
    protocol: TCP
    jump: ACCEPT
    source: "{{item}}"
    comment: "Allow from home"
  with_items:
    - "{{home_ip}}"
  no_log: true

- name: Allow all from local
  ansible.builtin.iptables:
    chain: INPUT
    protocol: TCP
    jump: ACCEPT
    source: "172.16.0.0/12"
    # interface: docker0
    comment: "Allow Docker network for NPM"

- name: Allow SSH
  ansible.builtin.iptables:
    chain: INPUT
    protocol: TCP
    ctstate: NEW,ESTABLISHED
    in_interface: "{{ ansible_default_ipv4.interface }}"
    destination_port: 22
    jump: ACCEPT
    source: "0.0.0.0/0"
    comment: "Allow SSH"
