- name: Get current iptables conf
  ansible.builtin.command: iptables -L -n
  register: iptables

- name: Print iptables
  ansible.builtin.debug:
    msg: "{{ iptables.stdout_lines }}"

- name: Save iptables conf
  ansible.builtin.command: iptables-save -f /etc/iptables/rules.v4
