- name: Create admin account in Portainer
  uri:
    url: "{{ portainer_api_url }}/api/users/admin/init"
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    body: '{"Username": "{{ portainer_admin_user }}", "Password": "{{ portainer_admin_password }}", "Role": 1}'
    status_code: 200

- name: "Authenticate with Portainer API"
  uri:
    url: "{{ portainer_api_url }}/api/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      username: "{{ portainer_admin_user }}"
      password: "{{ portainer_admin_password }}"
  register: auth_response
  changed_when: false
  ignore_errors: true

- name: "Check authentication response"
  fail:
    msg: "Failed to authenticate with Portainer API"
  when: "auth_response.status != 200"

- name: "Get JWT token from authentication response"
  set_fact:
    jwt_token: "{{ auth_response.json.jwt }}"
  when: auth_response.status == 200

- name: "Create endpoint"
  uri:
    url: "{{ portainer_api_url }}/api/endpoints"
    method: POST
    headers:
      Authorization: "Bearer {{ jwt_token }}"
      Content-Type: "application/json"
      Accept: "application/json, text/plain, */*"
    body_format: form-multipart
    body:
      ContainerEngine: "docker"
      Name: "LocalStack"
      EndpointCreationType: "1"
    return_content: yes
  register: get_stack_response
  when: jwt_token is defined
