- name: Create portainer volume
  docker_volume:
    name: portainer_data

- name: Run portainer
  docker_container:
    name: portainer
    restart_policy: always
    image: "portainer/portainer-ce:{{ portainer_version }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
