- name: Install Portainer
  ansible.builtin.include_tasks: install.yml

- name: "Check if account is working"
  uri:
    url: "{{ portainer_api_url }}/api/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      username: "{{ portainer_admin_user }}"
      password: "{{ portainer_admin_password }}"
  register: account_login
  changed_when: false
  ignore_errors: true

- name: Config Portainer
  ansible.builtin.include_tasks: config.yml
  when: account_login.failed
