- name: Create portainer volume
  docker_volume:
    name: portainer_data

- name: Run portainer
  docker_container:
    name: portainer
    restart_policy: always
    image: "portainer/portainer-ee:{{ portainer_version }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"

- name: Pause for 15 seconds
  pause:
    seconds: 15

- name: Create admin account in Portainer
  uri:
    url: "http://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:9000/api/users/admin/init"
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    body: '{"Username": "{{ portainer_admin_user }}", "Password": "{{ portainer_admin_password }}", "Role": 1}'
    status_code: 200
  tags: portainer_admin
