---
- name: Create git directory
  ansible.builtin.file:
    path: ~/git
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ final_user }}"

- name: Git clone
  ansible.builtin.git:
    repo: "git@github.com:{{ item }}.git"
    dest: "~/git/{{ item.split('/')[1] }}"
  become: true
  become_user: "{{ final_user }}"
  with_items: "{{ git_repos }}"
