---
- name: Create backup directory
  ansible.builtin.file:
    path: ~/backup
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ final_user }}"

- name: Copy backup config
  template:
    src: "templates/backup_conf.json.j2"
    dest: "~/backup/config.json"
    owner: "{{ final_user }}"
    group: "{{ final_user }}"
    mode: 0744
    lstrip_blocks: false
    trim_blocks: false
  become: true
  become_user: "{{ final_user }}"

- name: Copy backup script file
  copy:
    src: "files/backup.sh"
    dest: "~/backup/backup.sh"
    owner: "{{ final_user }}"
    group: "{{ final_user }}"
    mode: 0744
  become: true
  become_user: "{{ final_user }}"

- name: Create backup job at 3:00 everyday
  ansible.builtin.cron:
    name: "Backup docker volumes"
    minute: "0"
    hour: "3"
    job: 'cd /home/{{ final_user }}/backup/ && ./backup.sh config.json && curl {{ntfy_url}} -H "Title: {{ntfy_title}}" -d "{{backup_success.ntfy_content}}" -H "Tags: {{backup_success.ntfy_icon}}" || curl {{ntfy_url}} -H "Title: {{ntfy_title}}" -d "{{backup_error.ntfy_content}}" -H "Tags: {{backup_error.ntfy_icon}}"'
  become: true
  become_user: "{{ final_user }}"

- name: Copy restore script
  template:
    src: "templates/download_last_backup.sh.j2"
    dest: "~/backup/download_last_backup.sh"
    owner: "{{ final_user }}"
    group: "{{ final_user }}"
    mode: 0744
  become: true
  become_user: "{{ final_user }}"
