---
- name: Create Multimedia directory
  ansible.builtin.file:
    path: "{{ nfs_mount.mount_point }}/{{ nfs_mount.mount_directory }}"
    state: directory
    mode: "0777"

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ nfs_mount.ip }}:{{ nfs_mount.directory }}"
    path: "{{ nfs_mount.mount_point }}/{{ nfs_mount.mount_directory }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
