---
- name: Create user
  user:
    name: "{{ final_user }}"
    password: "{{ final_user_pass | password_hash('sha512') }}"
    shell: /bin/bash

- name: Add user to sudoers
  ansible.builtin.blockinfile:
    path: "/etc/sudoers.d/{{ final_user }}"
    block: |
      {{ final_user }} ALL=(ALL) NOPASSWD:ALL
    create: true

- name: Configure bashrc
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - "# Own"
    - "alias ll=ls -l"
    - "alias la=ls -a"
    - "alias lla=ls -lah"
    - "alias home='ssh ebenolt@home.ebe.ovh'"
    - "clear"
    - "neofetch --color_blocks off"
  become: true
  become_user: "{{ final_user }}"

- name: Create user SSH directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"
  become: true
  become_user: "{{ final_user }}"

- name: Set up SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ final_user }}"
    state: present
    key: "{{ lookup('file', 'files/SSH/Perso_SSH.pub') }}"
  become: true
  become_user: "{{ final_user }}"

- name: Copy SSH keys
  copy:
    src: "files/SSH/{{ item }}"
    dest: "~/.ssh/{{ item }}"
    owner: "{{ final_user }}"
    group: "{{ final_user }}"
    mode: 0700
  with_items:
    - "Perso_SSH"
    - "Perso_SSH.pub"
  become: true
  become_user: "{{ final_user }}"

- name: Change default SSH key
  ansible.builtin.blockinfile:
    path: "~/.ssh/config"
    block: |
      Host *
        IdentityFile ~/.ssh/Perso_SSH
        AddKeysToAgent yes
        StrictHostKeyChecking no
    create: true
  become: true
  become_user: "{{ final_user }}"
