---
- name: Check that backup config file exists
  stat:
    path: "~/git/s3-backuper/config.json"
  register: config_file
  become: true
  become_user: "{{ final_user }}"

- name: Create git directory
  ansible.builtin.file:
    path: ~/git
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ final_user }}"

- name: Git clone
  ansible.builtin.git:
    repo: "git@github.com:{{ item }}.git"
    dest: "~/git/{{ item.split('/')[1] }}"
  become: true
  when: not config_file.stat.exists
  become_user: "{{ final_user }}"
  with_items: "{{ git_repos }}"

- name: Copy backup config file
  copy:
    src: "files/backup_conf.json"
    dest: "~/git/s3-backuper/config.json"
    owner: "{{ final_user }}"
    group: "{{ final_user }}"
    mode: 0644
  when: config_file.stat.exists
  become: true
  become_user: "{{ final_user }}"

- name: Create backup job at 3:00 everyday
  ansible.builtin.cron:
    name: "Backup docker volumes"
    minute: "0"
    hour: "3"
    job: "cd /home/{{ final_user }}/git/s3-backuper && ./backup.sh config.json"
  become: true
  become_user: "{{ final_user }}"

- name: Copy restore script
  copy:
    src: "files/download_last_portainer_backup.sh"
    dest: "~/download_last_portainer_backup.sh"
    owner: "root"
    group: "root"
    mode: 0744
