# ansible-playbook playbook.yml -i inventory.ini --vault-password-file vault_pass -l Ebenolt-Infra -t runner --diff

- name: debug
  hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: debug
