# ansible-playbook playbook.yml -i inventory.ini --vault-password-file vault_pass -l Ebenolt-Infra -t runner --diff

- name: Installation et configuration de l'infra
  hosts: infra
  tasks:
    - ansible.builtin.import_role:
        name: system-prep
      tags: sysprep

    - ansible.builtin.import_role:
        name: monitoring
      tags: monitoring

    - ansible.builtin.import_role:
        name: user_conf
      tags: user_conf

    - ansible.builtin.import_role:
        name: portainer
      when: inventory_hostname in groups["Portainer"]
      tags: portainer

    - ansible.builtin.import_role:
        name: portainer_stack
      when: inventory_hostname in groups["Portainer"]
      tags: portainer_stack

    - ansible.builtin.import_role:
        name: runner
      when: inventory_hostname in groups["Runners"]
      tags: runner

    - ansible.builtin.import_role:
        name: keepalived
      when: inventory_hostname in groups["k8s"]
      tags: keepalived
