- name: Installation et configuration du VPS
  hosts: VPS
  tasks:
      - ansible.builtin.import_role:
          name: system-prep
        tags: sysprep


      - ansible.builtin.import_role:
          name: monitoring
        tags: monitoring

      - ansible.builtin.import_role:
          name: iptables
        tags: firewall