---
- name: Deploy Promtail to all servers
  hosts: infra
  tasks:
    - name: Include monitoring variables
      include_vars:
        dir: roles/monitoring/vars

    - name: Ensure loki_url is defined
      ansible.builtin.fail:
        msg: "loki_url variable is not defined. Please ensure it's set in your group_vars/all.yml or provide it via --extra-vars."
      when: loki_url is not defined
      
    - name: Install Promtail
      ansible.builtin.include_tasks: roles/monitoring/tasks/install_promtail.yml
      tags: promtail
