- name: Cleanup portainer stacks
  ansible.builtin.include_tasks: cleanup_stacks.yml

- name: Create portainer stacks
  ansible.builtin.include_tasks: update_stacks.yml
  vars:
    portainer_host: "{{ portainer_api_url }}"
    admin_user: "{{ portainer_admin_user }}"
    admin_password: "{{ portainer_admin_password }}"
    endpoint_id: "{{ portainer_endpoint_id }}"
    stack_name: "{{ item.name }}"
    stack_compose: "{{ lookup('ansible.builtin.template', role_path + '/templates/' + item.file) }}"
    stack_env: "{{ lookup('ansible.builtin.file', role_path + '/files/' + item.env) | default('') }}"
  with_items: "{{ stack }}"
