version: '3.8'

x-logging:
  &default-logging
  driver: "json-file"
  options: 
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8090:8080'
    volumes:
      - trainingData:/usr/share/tessdata
      - extraConfig:/configs
      - customFiles:/customFiles/
      - logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    container_name: pdf-editor
    logging: *default-logging
    restart: always
volumes:
  trainingData:
  extraConfig:
  customFiles:
  logs: