name: Test CI Local Runner

on:
  push:
    branches: [ "cicd" ]

jobs:
  checkout-and-reveal:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reveal
        run: git secret reveal -f -p $(echo $GPG_PASSPHRASE | base64 -d)
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  ansible-run:
    runs-on: self-hosted
    needs: [checkout-and-reveal]
    steps:
      - name: Run Playbook
        shell: bash
        working-directory: ./ansible
        run: pwd && export ANSIBLE_CONFIG=./ansible.cfg && ansible-playbook playbook.yml --check