version: "3.8"

volumes:
  mariadb-data:

services:
  database:
    image: mariadb:latest
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - PMA_HOST=database
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 20M

  
