version: "3.8"

volumes:
  nginx-data:
  nginx-certs:
  mariadb-data:
  access_pc-data:
  private:
  access_pc-gestion-data:
  access_pc-clients-data:

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-data:/data
      - nginx-certs:/etc/letsencrypt
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M

  database:
    image: mariadb:latest
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - PMA_HOST=database
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 20M

  access-pc: &service_default
    image: apresse/php_fpm_pdo_nginx:0.6
    container_name: access-pc
    restart: always
    # ports:
    #   - "8080:8080"
    volumes:
      - access_pc-data:/var/www/html
      - private:/var/www/private
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M
  
  access-pc-gestion:
    <<: *service_default
    container_name: access-pc-gestion
    # ports:
    #   - "8091:8080"
    volumes:
      - access_pc-gestion-data:/var/www/html
      - private:/var/www/private
    

  access-pc-clients:
    <<: *service_default
    container_name: access-pc-clients
    # ports:
    #   - "8091:8080"
    volumes:
      - access_pc-clients-data:/var/www/html
      - private:/var/www/private